plugins {
    id "net.fabricmc.fabric-loom" version "1.15.5"
    id "maven-publish"
}

def targetJavaVersion = Integer.parseInt(project.java_version)
def archiveBaseName = project.archives_base_name
def modVersion = project.mod_version
def minecraftVersion = project.minecraft_version
def loaderVersion = project.loader_version

version = modVersion
group = project.maven_group

base {
    archivesName = archiveBaseName
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

processResources {
    inputs.property "version", modVersion
    inputs.property "minecraft_version", minecraftVersion
    inputs.property "loader_version", loaderVersion

    filesMatching("fabric.mod.json") {
        expand(
            "version": modVersion,
            "minecraft_version": minecraftVersion,
            "loader_version": loaderVersion
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = targetJavaVersion
}

jar {
    from("LICENSE") {
        rename { "${it}_${archiveBaseName}" }
    }
}
