# Fabric Properties
minecraft_version=26.2
minecraft_version_range=>=26.1 <26.4
loader_version=0.19.3
fabric_version=0.152.1+26.2
fabric_api_dependency=*
modmenu_version=20.0.3
cloth_config_version=26.2.155

# Mod Properties
mod_id=clickfeeder
mod_version=1.3.0
maven_group=com.clickfeeder
archives_base_name=clickfeeder

# Java
java_version=25

# Gradle
org.gradle.jvmargs=-Xmx2G
